# docker-compose のバージョン
version: '3'

# 各コンテナの情報
services:
  migration:
    container_name: migration
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
    env_file: .env
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./:/go/src/github.com/kenkonno/gantt-chart-proto/backend/
    # docker-compose run 実行時に実行されるコマンド
    tty:
      true
    command: go run ./main.go
