version: '3'

services:

  gantt_postgres:
    container_name: gantt_postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "5433:5432"
    env_file: .env
    volumes:
      - dbdata_gantt:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  gantt_api:
    container_name: gantt_api
    ports:
      - "8080:8080"
    depends_on:
      gantt_postgres:
        condition: service_healthy
      gantt_session:
        condition: service_started
    build:
      context: .
      dockerfile: ./docker/api/DockerfileForProvision
    env_file: .env
    volumes:
      - ./:/go/src/github.com/kenkonno/gantt-chart-proto/backend/
    tty:
      true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gantt_migration:
    container_name: gantt_migration
    build:
      context: .
      dockerfile: ./docker/migration/DockerfileForProvision
    env_file: .env
    volumes:
      - ./:/go/src/github.com/kenkonno/gantt-chart-proto/backend/
    tty:
      true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gantt_session:
    container_name: gantt_session
    build:
      context: .
      dockerfile: ./docker/session/Dockerfile
    ports:
      - "6379:6379"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gantt_web:
    container_name: gantt_web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  dbdata_gantt:
    external: true
