# docker-compose のバージョン
version: '3'

# 各コンテナの情報
services:

  # postgres サービス
  gantt_postgres:
    # コンテナの名前
    container_name: gantt_postgres
    # Dockerfile のディレクトリパス
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    # postgres 設定
    env_file: .env
    volumes:
      - dbdata_gantt:/var/lib/postgresql/data
  #      - ./docker/postgres/init/:/docker-entrypoint-initdb.d/

    # golang アプリケーション
  gantt_api:
    container_name: gantt_api
    ports:
      - "8081:8081"
    # postgres をビルドした後に app をビルド
#    depends_on:
#      - postgres
    # Dockerfile を指定
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    env_file: .env
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./:/go/src/github.com/kenkonno/gantt-chart-proto/backend/
    # docker-compose run 実行時に実行されるコマンド
    tty:
      true
    command: CompileDaemon -command="./api" -include="*.go" -polling

  # golang   batch
  gantt_batch:
    container_name: gantt_batch
    # postgres をビルドした後に app をビルド
#    depends_on:
#      - postgres
    # Dockerfile を指定
    build:
      context: .
      dockerfile: ./docker/batch/Dockerfile
    env_file: .env
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./:/go/src/github.com/kenkonno/gantt-chart-proto/backend/
    # docker-compose run 実行時に実行されるコマンド
    tty:
      true

  gantt_migration:
    container_name: gantt_migration
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
    env_file: .env
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./:/go/src/github.com/kenkonno/gantt-chart-proto/backend/
    # docker-compose run 実行時に実行されるコマンド
    tty:
      true
    command: go run ./main.go

volumes:
  dbdata_gantt:
    external: true
