/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type User struct {

	Id *int32 `json:"id,omitempty"`

	DepartmentId int32 `json:"department_id"`

	LimitOfOperation float32 `json:"limit_of_operation"`

	LastName string `json:"lastName" binding:"min=1"`

	FirstName string `json:"firstName" binding:"min=1"`

	Password string `json:"password" binding:"min=0"`

	Email string `json:"email" binding:"min=1"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt int64 `json:"updated_at,omitempty"`

	Role string `json:"role"`
}
