/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type TicketUser struct {
	Id *int32 `json:"id,omitempty" form:"id,omitempty"`

	TicketId int32 `json:"ticket_id" form:"ticket_id" binding:"min=1"`

	UserId int32 `json:"user_id" form:"user_id" binding:"min=1"`

	Order int32 `json:"order,omitempty" form:"order,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty" form:"created_at,omitempty"`

	UpdatedAt int32 `json:"updated_at,omitempty" form:"updated_at,omitempty"`
}
