/*
 * TwitchClipsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type Clip struct {

	BroadcasterName string `json:"broadcasterName"`

	ProfileImageUrl string `json:"profileImageUrl"`

	VideoId string `json:"videoId"`

	Title string `json:"title"`

	ViewCount int32 `json:"viewCount"`

	VodOffset int32 `json:"vodOffset"`

	Duration float32 `json:"duration"`

	Order int32 `json:"order"`

	ThumbnailUrl string `json:"thumbnailUrl"`

	GameName string `json:"gameName"`

	BroadcasterId string `json:"broadcasterId"`

	ClipId string `json:"clipId"`

	GameThumbnailUrl string `json:"gameThumbnailUrl"`

	PlaylistClipId float32 `json:"playlistClipId,omitempty"`
}
