/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type History struct {
	Id int32 `json:"id,omitempty" form:"id,omitempty"`

	FacilityId int32 `json:"facility_id,omitempty" form:"facility_id,omitempty"`

	Name string `json:"name,omitempty" form:"name,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty" form:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty" form:"updated_at,omitempty"`
}
