/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type PostTicketUsersRequest struct {

	TicketId int32 `json:"ticketId"`

	UserIds []int32 `json:"userIds"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
