/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type WorkHour struct {
	ProcessId int32 `json:"process_id,omitempty" form:"process_id,omitempty"`

	WorkHour int32 `json:"work_hour,omitempty" form:"work_hour,omitempty"`
}
