/*
 * TwitchClipsApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type PlaylistClip struct {

	Id float32 `json:"id,omitempty"`

	PlaylistId float32 `json:"playlistId,omitempty"`

	ClipId string `json:"clipId,omitempty"`
}
