/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type GetSimulationMasterDiffResponse struct {

	BeforeProcesses []Process `json:"beforeProcesses"`

	DiffProcesses []Process `json:"diffProcesses,omitempty"`

	AfterProcesses []Process `json:"afterProcesses"`

	BeforeDepartments []Department `json:"beforeDepartments"`

	DiffDepartments []Department `json:"diffDepartments,omitempty"`

	AfterDepartments []Department `json:"afterDepartments"`

	BeforeUsers []User `json:"beforeUsers"`

	DiffUsers []User `json:"diffUsers,omitempty"`

	AfterUsers []User `json:"afterUsers"`

	BeforeUnits []Unit `json:"beforeUnits"`

	DiffUnits []Unit `json:"diffUnits,omitempty"`

	AfterUnits []Unit `json:"afterUnits"`

	BeforeHolidays []Holiday `json:"beforeHolidays"`

	DiffHolidays []Holiday `json:"diffHolidays,omitempty"`

	AfterHolidays []Holiday `json:"afterHolidays"`

	BeforeMilestones []Milestone `json:"beforeMilestones"`

	DiffMilestones []Milestone `json:"diffMilestones,omitempty"`

	AfterMilestones []Milestone `json:"afterMilestones"`
}
