/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type PostUnitsDuplicateRequest struct {

	// ID of the unit to duplicate
	UnitId int32 `json:"unitId" form:"unitId"`

	// new unit name
	UnitName string `json:"unitName,omitempty" form:"unitName,omitempty"`

	// Flag to copy ProcessId field from source ticket
	CopyProcessId bool `json:"copyProcessId" form:"copyProcessId"`

	// Flag to copy DepartmentId field from source ticket
	CopyDepartmentId bool `json:"copyDepartmentId" form:"copyDepartmentId"`

	// Flag to copy Estimate field from source ticket
	CopyEstimate bool `json:"copyEstimate" form:"copyEstimate"`

	// Flag to copy NumberOfWorker field from source ticket
	CopyNumberOfWorker bool `json:"copyNumberOfWorker" form:"copyNumberOfWorker"`

	// Flag to copy DaysAfter field from source ticket
	CopyDaysAfter bool `json:"copyDaysAfter" form:"copyDaysAfter"`

	// Flag to copy StartDate field from source ticket
	CopyStartDate bool `json:"copyStartDate" form:"copyStartDate"`

	// Flag to copy EndDate field from source ticket
	CopyEndDate bool `json:"copyEndDate" form:"copyEndDate"`

	// Flag to copy ProgressPercent field from source ticket
	CopyProgressPercent bool `json:"copyProgressPercent" form:"copyProgressPercent"`

	// Flag to copy Memo field from source ticket
	CopyMemo bool `json:"copyMemo" form:"copyMemo"`

	// Flag to copy copyTicketUser field from source ticket
	CopyTicketUser bool `json:"copyTicketUser" form:"copyTicketUser"`
}
