/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

// User - 
type User struct {

	Id *int32 `json:"id"`

	Password string `json:"password"`

	Email string `json:"email"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt int `json:"updated_at,omitempty"`
}
