/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

// Milestone -
type Milestone struct {
	Id *int32 `json:"id,omitempty" form:"id,omitempty"`

	FacilityId int32 `json:"facility_id" form:"facility_id" binding:"min=1"`

	Date time.Time `json:"date" form:"date"`

	Description string `json:"description" form:"description" binding:"min=1"`

	Order int32 `json:"order" form:"order" binding:"min=1"`

	CreatedAt time.Time `json:"created_at,omitempty" form:"created_at,omitempty"`

	UpdatedAt int32 `json:"updated_at,omitempty" form:"updated_at,omitempty"`
}
