/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type ScheduleAlert struct {
	FacilityId int32 `json:"facility_id" form:"facility_id"`

	FacilityName string `json:"facility_name" form:"facility_name"`

	UnitId int32 `json:"unit_id" form:"unit_id"`

	UnitName string `json:"unit_name" form:"unit_name"`

	ProcessId int32 `json:"process_id" form:"process_id"`

	ProcessName string `json:"process_name" form:"process_name"`

	EndDate time.Time `json:"end_date" form:"end_date"`

	StartDate time.Time `json:"start_date" form:"start_date"`

	ActualProgressDate time.Time `json:"actual_progress_date,omitempty" form:"actual_progress_date,omitempty"`

	ProgressPercent float32 `json:"progress_percent" form:"progress_percent" binding:"min=1"`

	DelayDays float32 `json:"delay_days" form:"delay_days"`

	TicketId int32 `json:"ticket_id,omitempty" form:"ticket_id,omitempty"`
}
