/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type PostHistoriesRequest struct {
	FacilityId int32 `json:"facility_id,omitempty" form:"facility_id,omitempty"`

	Name string `json:"name,omitempty" form:"name,omitempty"`
}
