/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type GetSimulationMasterDiffResponse struct {

	BeforeProcesses []Process `json:"beforeProcesses" form:"beforeProcesses"`

	DiffProcesses []Process `json:"diffProcesses,omitempty" form:"diffProcesses,omitempty"`

	AfterProcesses []Process `json:"afterProcesses" form:"afterProcesses"`

	BeforeDepartments []Department `json:"beforeDepartments" form:"beforeDepartments"`

	DiffDepartments []Department `json:"diffDepartments,omitempty" form:"diffDepartments,omitempty"`

	AfterDepartments []Department `json:"afterDepartments" form:"afterDepartments"`

	BeforeUsers []User `json:"beforeUsers" form:"beforeUsers"`

	DiffUsers []User `json:"diffUsers,omitempty" form:"diffUsers,omitempty"`

	AfterUsers []User `json:"afterUsers" form:"afterUsers"`

	BeforeUnits []Unit `json:"beforeUnits" form:"beforeUnits"`

	DiffUnits []Unit `json:"diffUnits,omitempty" form:"diffUnits,omitempty"`

	AfterUnits []Unit `json:"afterUnits" form:"afterUnits"`

	BeforeHolidays []Holiday `json:"beforeHolidays" form:"beforeHolidays"`

	DiffHolidays []Holiday `json:"diffHolidays,omitempty" form:"diffHolidays,omitempty"`

	AfterHolidays []Holiday `json:"afterHolidays" form:"afterHolidays"`

	BeforeMilestones []Milestone `json:"beforeMilestones" form:"beforeMilestones"`

	DiffMilestones []Milestone `json:"diffMilestones,omitempty" form:"diffMilestones,omitempty"`

	AfterMilestones []Milestone `json:"afterMilestones" form:"afterMilestones"`
}
