/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

// OperationSetting - 
type OperationSetting struct {

	Id *int32 `json:"id,omitempty"`

	FacilityId int32 `json:"facility_id,omitempty"`

	UnitId int32 `json:"unit_id,omitempty"`

	WorkHours []WorkHour `json:"workHours" binding:"min=1"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt int32 `json:"updated_at,omitempty"`
}
