/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type GetTicketMemoIdResponse struct {

	Memo string `json:"memo" form:"memo"`

	UpdatedAt int32 `json:"updated_at" form:"updated_at"`
}
