/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type PileUpByFacility struct {

	FacilityId int32 `json:"facilityId"`

	Labels []float32 `json:"labels"`

	Styles []map[string]interface{} `json:"styles"`

	HasError bool `json:"hasError"`
}
