/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type GetTicketDailyWeightsIdRequest struct {
	TicketId int32 `json:"ticketId,omitempty" form:"ticketId,omitempty"`

	Date time.Time `json:"date,omitempty" form:"date,omitempty"`
}
