/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type GetDetectWorkOutsideEmploymentPeriodsRequest struct {

	UserId int32 `json:"userId" form:"userId"`

	EmploymentStartDate time.Time `json:"employmentStartDate" form:"employmentStartDate"`

	EmploymentEndDate time.Time `json:"employmentEndDate,omitempty" form:"employmentEndDate,omitempty"`
}
