/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

// PileUp - 
type PileUp struct {

	GanttGroups string `json:"gantt_groups" form:"gantt_groups" binding:"min=1"`

	Holidays int32 `json:"holidays" form:"holidays" binding:"min=1"`
}
