/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type PostTicketDailyWeightsResponse struct {
	TicketDailyWeight TicketDailyWeight `json:"ticketDailyWeight,omitempty" form:"ticketDailyWeight,omitempty"`
}
