/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type Ticket struct {

	Id *int32 `json:"id,omitempty" form:"id,omitempty"`

	GanttGroupId int32 `json:"gantt_group_id" form:"gantt_group_id" binding:"min=1"`

	ProcessId *int32 `json:"process_id,omitempty" form:"process_id,omitempty"`

	DepartmentId *int32 `json:"department_id,omitempty" form:"department_id,omitempty"`

	LimitDate *time.Time `json:"limit_date,omitempty" form:"limit_date,omitempty"`

	Estimate *int32 `json:"estimate,omitempty" form:"estimate,omitempty"`

	NumberOfWorker *int32 `json:"number_of_worker,omitempty" form:"number_of_worker,omitempty"`

	DaysAfter *int32 `json:"days_after,omitempty" form:"days_after,omitempty"`

	StartDate *time.Time `json:"start_date,omitempty" form:"start_date,omitempty"`

	EndDate *time.Time `json:"end_date,omitempty" form:"end_date,omitempty"`

	ProgressPercent *int32 `json:"progress_percent,omitempty" form:"progress_percent,omitempty"`

	Memo string `json:"memo,omitempty" form:"memo,omitempty"`

	Order int32 `json:"order" form:"order"`

	CreatedAt time.Time `json:"created_at,omitempty" form:"created_at,omitempty"`

	UpdatedAt int32 `json:"updated_at,omitempty" form:"updated_at,omitempty"`
}
