/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type Department struct {

	Id *int32 `json:"id,omitempty" form:"id,omitempty"`

	Name string `json:"name" form:"name" binding:"min=1"`

	Order int32 `json:"order" form:"order"`

	CreatedAt time.Time `json:"created_at,omitempty" form:"created_at,omitempty"`

	UpdatedAt int32 `json:"updated_at,omitempty" form:"updated_at,omitempty"`
}
