/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

// Ticket -
type Ticket struct {
	Id *int32 `json:"id,omitempty"`

	GanttGroupId int32 `json:"gantt_group_id" binding:"min=1"`

	ProcessId *int32 `json:"process_id,omitempty"`

	DepartmentId *int32 `json:"department_id,omitempty"`

	LimitDate *time.Time `json:"limit_date,omitempty"`

	Estimate *int32 `json:"estimate,omitempty"`

	NumberOfWorker *int32 `json:"number_of_worker,omitempty"`

	DaysAfter *int32 `json:"days_after,omitempty"`

	StartDate *time.Time `json:"start_date,omitempty"`

	EndDate *time.Time `json:"end_date,omitempty"`

	ProgressPercent *int32 `json:"progress_percent,omitempty"`

	Order int32 `json:"order" binding:"min=0"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt int `json:"updated_at,omitempty"`
}
