/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type TicketDailyWeight struct {
	Id *int32 `json:"id,omitempty" form:"id,omitempty"`

	TicketId int32 `json:"ticketId" form:"ticketId"`

	WorkHour int32 `json:"workHour" form:"workHour"`

	Date int32 `json:"date" form:"date"`

	CreatedAt time.Time `json:"created_at,omitempty" form:"created_at,omitempty"`

	UpdatedAt int32 `json:"updated_at,omitempty" form:"updated_at,omitempty"`
}
