/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type SimulationLock struct {

	SimulationName string `json:"simulationName"`

	Status string `json:"status"`

	LockedAt time.Time `json:"lockedAt"`

	LockedBy int32 `json:"lockedBy"`
}
