/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type DefaultPileUp struct {

	DepartmentId int32 `json:"departmentId,omitempty"`

	AssignedUser AssignedPileUp `json:"assignedUser,omitempty"`

	UnAssignedPileUp UnAssingedPileUp `json:"unAssignedPileUp,omitempty"`

	NoOrdersReceivedPileUp NoOrdersReceivedPileUp `json:"noOrdersReceivedPileUp,omitempty"`

	Labels []float32 `json:"labels"`

	Styles []map[string]interface{} `json:"styles"`

	Display bool `json:"display"`
}
