/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

type GetFacilitySharedLinksIdResponse struct {

	FacilitySharedLink FacilitySharedLink `json:"facilitySharedLink,omitempty" form:"facilitySharedLink,omitempty"`
}
