/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models-generator.tech)
 */

package openapi_models

import (
	"time"
)

type Facility struct {

	Id *int32 `json:"id,omitempty"`

	Name string `json:"name" binding:"min=1"`

	TermFrom time.Time `json:"term_from"`

	TermTo time.Time `json:"term_to"`

	Order int32 `json:"order,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt int32 `json:"updated_at,omitempty"`

	Status string `json:"status"`

	Type string `json:"type"`

	ShipmentDueDate time.Time `json:"shipment_due_date"`
}
