/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapi_models_modelstools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi_models_models-generator.tech)
 */

package openapi_models_models

type GetUsersIdRequest struct {

	Id int32 `json:"id,omitempty"`
}
