/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (

	"github.com/kenkonno/gantt-chart-proto/backend/api/interactor/users"
	"github.com/kenkonno/gantt-chart-proto/backend/api/interactor/users_id"

	"github.com/kenkonno/gantt-chart-proto/backend/api/openapi_models"
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetUsers - GetUsers
func GetUsers(c *gin.Context) {
	var r openapi_models.GetUsersResponse
	r = users.GetUsersInvoke(c)
	c.JSON(http.StatusOK, r)
}

// GetUsersId - GetUsersId
func GetUsersId(c *gin.Context) {
	var r openapi_models.GetUsersIdResponse
	r = users_id.GetUsersIdInvoke(c)
	c.JSON(http.StatusOK, r)
}

