/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ApiHistoriesGet - Get history snapshots for a facility
func ApiHistoriesGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ApiHistoriesIdDelete - Delete a history snapshot
func ApiHistoriesIdDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ApiHistoriesIdPut - Update a history snapshot's name
func ApiHistoriesIdPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ApiHistoriesPost - Create a history snapshot
func ApiHistoriesPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
