/*
 * GanttChartApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (

	"github.com/kenkonno/gantt-chart-proto/backend/api/interactor/users"

	"github.com/kenkonno/gantt-chart-proto/backend/api/openapi_models"
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteUsersId - DeleteUsersId
func DeleteUsersId(c *gin.Context) {
	var r openapi_models.DeleteUsersIdResponse
	r = users.DeleteUsersIdInvoke(c)
	c.JSON(http.StatusOK, r)
}

// GetUsers - GetUsers
func GetUsers(c *gin.Context) {
	var r openapi_models.GetUsersResponse
	r = users.GetUsersInvoke(c)
	c.JSON(http.StatusOK, r)
}

// GetUsersId - GetUsersId
func GetUsersId(c *gin.Context) {
	var r openapi_models.GetUsersIdResponse
	r = users.GetUsersIdInvoke(c)
	c.JSON(http.StatusOK, r)
}

// PostUsers - PostUsers
func PostUsers(c *gin.Context) {
	var r openapi_models.PostUsersResponse
	r = users.PostUsersInvoke(c)
	c.JSON(http.StatusOK, r)
}

// PostUsersId - PostUsersId
func PostUsersId(c *gin.Context) {
	var r openapi_models.PostUsersIdResponse
	r = users.PostUsersIdInvoke(c)
	c.JSON(http.StatusOK, r)
}

