title: GetOperationSettingsResponse
type: object
properties:
  operationSettings:
    type: array
    items:
      $ref: '../api.yaml#/components/schemas/OperationSetting'
required:
  - operationSettings
